package xxgam.oracle.apps.xbol.tm.InvoiceAs.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailVORowImpl extends OAViewRowImpl {
    public static final int FOLIOFLETE = 0;
    public static final int TRANSPORT = 1;
    public static final int FOLIOSINTRAMO = 2;
    public static final int TRAMO = 3;
    public static final int FEE = 4;
    public static final int IVAFLAG = 5;
    public static final int RETENTIONFLAG = 6;
    public static final int IVAMFLAG = 7;
    public static final int RETENTIONMFLAG = 8;
    public static final int CURRENCY = 9;
    public static final int PROVIDER = 10;
    public static final int INVOICESTATUS = 11;
    public static final int CHECKBOX = 12;

    /**This is the default constructor (do not remove)
     */
    public DetailVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute FolioFlete
     */
    public String getFolioFlete() {
        return (String) getAttributeInternal(FOLIOFLETE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FolioFlete
     */
    public void setFolioFlete(String value) {
        setAttributeInternal(FOLIOFLETE, value);
    }

    /**Gets the attribute value for the calculated attribute Transport
     */
    public String getTransport() {
        return (String) getAttributeInternal(TRANSPORT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Transport
     */
    public void setTransport(String value) {
        setAttributeInternal(TRANSPORT, value);
    }

    /**Gets the attribute value for the calculated attribute Foliosintramo
     */
    public Number getFoliosintramo() {
        return (Number) getAttributeInternal(FOLIOSINTRAMO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Foliosintramo
     */
    public void setFoliosintramo(Number value) {
        setAttributeInternal(FOLIOSINTRAMO, value);
    }

    /**Gets the attribute value for the calculated attribute Tramo
     */
    public Number getTramo() {
        return (Number) getAttributeInternal(TRAMO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Tramo
     */
    public void setTramo(Number value) {
        setAttributeInternal(TRAMO, value);
    }

    /**Gets the attribute value for the calculated attribute Fee
     */
    public Number getFee() {
        return (Number) getAttributeInternal(FEE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Fee
     */
    public void setFee(Number value) {
        setAttributeInternal(FEE, value);
    }

    /**Gets the attribute value for the calculated attribute IvaFlag
     */
    public String getIvaFlag() {
        return (String) getAttributeInternal(IVAFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IvaFlag
     */
    public void setIvaFlag(String value) {
        setAttributeInternal(IVAFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute RetentionFlag
     */
    public String getRetentionFlag() {
        return (String) getAttributeInternal(RETENTIONFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RetentionFlag
     */
    public void setRetentionFlag(String value) {
        setAttributeInternal(RETENTIONFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute IvaMFlag
     */
    public String getIvaMFlag() {
        return (String) getAttributeInternal(IVAMFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IvaMFlag
     */
    public void setIvaMFlag(String value) {
        setAttributeInternal(IVAMFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute RetentionMFlag
     */
    public String getRetentionMFlag() {
        return (String) getAttributeInternal(RETENTIONMFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RetentionMFlag
     */
    public void setRetentionMFlag(String value) {
        setAttributeInternal(RETENTIONMFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute Currency
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**Gets the attribute value for the calculated attribute Provider
     */
    public String getProvider() {
        return (String) getAttributeInternal(PROVIDER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Provider
     */
    public void setProvider(String value) {
        setAttributeInternal(PROVIDER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case FOLIOFLETE:
            return getFolioFlete();
        case TRANSPORT:
            return getTransport();
        case FOLIOSINTRAMO:
            return getFoliosintramo();
        case TRAMO:
            return getTramo();
        case FEE:
            return getFee();
        case IVAFLAG:
            return getIvaFlag();
        case RETENTIONFLAG:
            return getRetentionFlag();
        case IVAMFLAG:
            return getIvaMFlag();
        case RETENTIONMFLAG:
            return getRetentionMFlag();
        case CURRENCY:
            return getCurrency();
        case PROVIDER:
            return getProvider();
        case INVOICESTATUS:
            return getInvoiceStatus();
        case CHECKBOX:
            return getCheckBox();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case INVOICESTATUS:
            setInvoiceStatus((String)value);
            return;
        case CHECKBOX:
            setCheckBox((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute CheckBox
     */
    public Boolean getCheckBox() {
        return (Boolean) getAttributeInternal(CHECKBOX);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CheckBox
     */
    public void setCheckBox(Boolean value) {
        setAttributeInternal(CHECKBOX, value);
    }


    /**Gets the attribute value for the calculated attribute InvoiceStatus
     */
    public String getInvoiceStatus() {
        return (String) getAttributeInternal(INVOICESTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceStatus
     */
    public void setInvoiceStatus(String value) {
        setAttributeInternal(INVOICESTATUS, value);
    }
}
