package xxgam.oracle.apps.xbol.tm.InvoiceAs.server;

import oracle.apps.fnd.framework.OAViewObject;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceAsAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public InvoiceAsAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxgam.oracle.apps.xbol.tm.InvoiceAs.server", /* package name */
      "InvoiceAsAMLocal" /* Configuration Name */);
    }


    /**custom methods*/
     public void filterInvoices(String StringProvider){
     
     System.out.println("InvoiceAsAMImpl Entro a filterInvoices");
         DetailVOImpl detailVOImpl = getDetailVO1();         
         System.out.println(" InvoiceAsAMImpl detailVOImpl");
         ViewCriteria vc = detailVOImpl.createViewCriteria();
         
         System.out.println("InvoiceAsAMImpl creado view criteria");
         ViewCriteriaRow vcr1    = vc.createViewCriteriaRow();
         System.out.println("InvoiceAsAMImpl creado view criteria row");

         
         System.out.println("InvoiceAsAMImpl inicializados viewCriteria y viewCriteriaRow");
         if (StringProvider != null){
             System.out.println("InvoiceAsAMImpl proveedor no nulo");
             vcr1.setAttribute("Provider",StringProvider);

         }
         vc.add(vcr1);

        detailVOImpl.applyViewCriteria(vc);

        System.out.println(detailVOImpl.getQuery());

        detailVOImpl.executeQuery();
        
         
     }

    public void checker (){
    System.out.println("InvoiceAsAMImpl checker");
        /*String aux ;
        DetailVOImpl voRU = getDetailVO1();
       System.out.println("checkerDetail");
        RowSetIterator rowSetIterator = voRU.createRowSetIterator(null);
        
        do{
            System.out.println("entro a do");
              DetailVORowImpl detailVORowImpl = (DetailVORowImpl)rowSetIterator.next();
            System.out.println("rowSetIterator.next ");
            
            
             if (detailVORowImpl.getCheckBox() ){
             System.out.println("entro a if");
              aux = (String)detailVORowImpl.getCheckBox();
              System.out.println("aux: "+aux);
              }
              else { 
              aux = "false";
              System.out.println("aux: "+aux);
              }
         
              System.out.println("InvoiceAsAMImpl Check " + aux );
             // System.out.println("flete: " + detailVORowImpl.getFolioFlete());
            if (aux.equals("true")){
                detailVORowImpl.setInvoiceStatus("Conciliado");
                System.out.println("estatus del conciliado " + detailVORowImpl.getInvoiceStatus());
            }
              apply();  
          }
        while(rowSetIterator.hasNext());*/
    }

    public void apply (){
        getTransaction().commit();

    }

    /**Container's getter for detailVO1
     */

    /**Container's getter for DetailVO1
     */
    public DetailVOImpl getDetailVO1() {
        return (DetailVOImpl)findViewObject("DetailVO1");
    }
}
