package xxgam.oracle.apps.xbol.tm.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DistributionVORowImpl extends OAViewRowImpl {
    public static final int DISTRIBUTIONID = 0;
    public static final int CODE = 1;
    public static final int DNAME = 2;
    public static final int MOVEMENTTYPE = 3;
    public static final int AREA = 4;
    public static final int DATEFROM = 5;
    public static final int DATETO = 6;
    public static final int ATTRIBUTE1 = 7;
    public static final int ATTRIBUTE2 = 8;
    public static final int ATTRIBUTE3 = 9;
    public static final int ATTRIBUTE4 = 10;
    public static final int ATTRIBUTE5 = 11;
    public static final int ATTRIBUTE6 = 12;
    public static final int ATTRIBUTE7 = 13;
    public static final int ATTRIBUTE8 = 14;
    public static final int ATTRIBUTE9 = 15;
    public static final int ATTRIBUTE10 = 16;

    /**This is the default constructor (do not remove)
     */
    public DistributionVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute DistributionId
     */
    public Number getDistributionId() {
        return (Number) getAttributeInternal(DISTRIBUTIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DistributionId
     */
    public void setDistributionId(Number value) {
        setAttributeInternal(DISTRIBUTIONID, value);
    }

    /**Gets the attribute value for the calculated attribute Code
     */
    public String getCode() {
        return (String) getAttributeInternal(CODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Code
     */
    public void setCode(String value) {
        setAttributeInternal(CODE, value);
    }

    /**Gets the attribute value for the calculated attribute DName
     */
    public String getDName() {
        return (String) getAttributeInternal(DNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DName
     */
    public void setDName(String value) {
        setAttributeInternal(DNAME, value);
    }

    /**Gets the attribute value for the calculated attribute MovementType
     */
    public String getMovementType() {
        return (String) getAttributeInternal(MOVEMENTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MovementType
     */
    public void setMovementType(String value) {
        setAttributeInternal(MOVEMENTTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute Area
     */
    public String getArea() {
        return (String) getAttributeInternal(AREA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Area
     */
    public void setArea(String value) {
        setAttributeInternal(AREA, value);
    }

    /**Gets the attribute value for the calculated attribute DateFrom
     */
    public Date getDateFrom() {
        return (Date) getAttributeInternal(DATEFROM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DateFrom
     */
    public void setDateFrom(Date value) {
        setAttributeInternal(DATEFROM, value);
    }

    /**Gets the attribute value for the calculated attribute DateTo
     */
    public Date getDateTo() {
        return (Date) getAttributeInternal(DATETO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DateTo
     */
    public void setDateTo(Date value) {
        setAttributeInternal(DATETO, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DISTRIBUTIONID:
            return getDistributionId();
        case CODE:
            return getCode();
        case DNAME:
            return getDName();
        case MOVEMENTTYPE:
            return getMovementType();
        case AREA:
            return getArea();
        case DATEFROM:
            return getDateFrom();
        case DATETO:
            return getDateTo();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
