package xxgam.oracle.apps.xbol.tm.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LovAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public LovAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxgam.oracle.apps.xbol.tm.lov.server", /* package name */
      "LovAMLocal" /* Configuration Name */);
    }


    /**Container's getter for DestinationVO1
     */
    public DestinationVOImpl getDestinationVO1() {
        return (DestinationVOImpl)findViewObject("DestinationVO1");
    }

    /**Container's getter for PriorityVO1
     */
    public PriorityVOImpl getPriorityVO1() {
        return (PriorityVOImpl)findViewObject("PriorityVO1");
    }

    /**Container's getter for OriginVO1
     */
    public OriginVOImpl getOriginVO1() {
        return (OriginVOImpl)findViewObject("OriginVO1");
    }

    /**Container's getter for DistributionVO1
     */
    public DistributionVOImpl getDistributionVO1() {
        return (DistributionVOImpl)findViewObject("DistributionVO1");
    }

    /**Container's getter for ProvidersVO1
     */
    public ProvidersVOImpl getProvidersVO1() {
        return (ProvidersVOImpl)findViewObject("ProvidersVO1");
    }

    /**Container's getter for ZonesVO1
     */
    public ZonesVOImpl getZonesVO1() {
        return (ZonesVOImpl)findViewObject("ZonesVO1");
    }

    /**Container's getter for TransportModeVO1
     */
    public TransportModeVOImpl getTransportModeVO1() {
        return (TransportModeVOImpl)findViewObject("TransportModeVO1");
    }
}
