package xxgam.oracle.apps.xbol.tm.extracost.server;

import java.sql.SQLException;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import oracle.apps.fnd.framework.webui.OAPageContext;
import oracle.apps.fnd.framework.webui.beans.OAWebBean;

import oracle.apps.fnd.framework.webui.beans.message.OAMessageDateFieldBean;
import oracle.apps.fnd.framework.webui.beans.message.OAMessageTextInputBean;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExtraCostImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public ExtraCostImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxgam.oracle.apps.xbol.tm.extracost.server", /* package name */
      "ExtraCostLocal" /* Configuration Name */);
    }


    public void fillTable(String strProveedor, String strPrioridad, 
                                 Date strCreationDate) {
        ExtraCostVOImpl extraCostVOImpl = getExtraCostVO1();  
        
        //creamos el criterio
        ViewCriteria vc = extraCostVOImpl.createViewCriteria();
        ViewCriteriaRow vcr1 = vc.createViewCriteriaRow();
        
        if(null != strProveedor && !"".equals(strProveedor)){
            System.out.println("Proveedor no nulo");
            vcr1.setAttribute("Provider",strProveedor);  
        }//fin de if(null != strProveedor)
        
        if(null != strPrioridad && !"".equals(strPrioridad)){
            System.out.println("Prioridad no nula");
            //vcr1.setAttribute();
        }//fin de if(null != strPrioridad)
        
        if(null != strCreationDate && !"".equals(strCreationDate)){
            System.out.println("Fecha de creacion no nula");   
            ///Date creaDate = (Date)strCreationDate.valueOf();
             System.out.println("strCreationDate:       "+strCreationDate);
            vcr1.setAttribute("CreationDate",strCreationDate);
        }//fin de if(null != strCreationDate)
        
        //vcr1.setAttribute("Status","En proceso");
        vc.add(vcr1);
        extraCostVOImpl.applyViewCriteria(vc);
        extraCostVOImpl.executeQuery();
        
    }

    /**Container's getter for ExtraCostVO1
     */
    public ExtraCostVOImpl getExtraCostVO1() {
        return (ExtraCostVOImpl)findViewObject("ExtraCostVO1");
    }

    public void getVariables(OAPageContext pageContext, OAWebBean webBean) {
        String strProveedor     = pageContext.getParameter("Proveedor");
        String strPrioridad     = pageContext.getParameter("Prioridad");
        OAMessageDateFieldBean oMessageTextInputBean = (OAMessageDateFieldBean)webBean.findChildRecursive("CreationDate");
        oracle.jbo.domain.Date strCreationDate = null;
        try {
            strCreationDate = new oracle.jbo.domain.Date(oMessageTextInputBean.getValue(pageContext));
        } catch (SQLException e) {
            System.out.println("No se encontro el campo tipo fecha");
        }
        String strDocument      = pageContext.getParameter("Document");
        String strDocument1     = pageContext.getParameter("Document1");
        System.out.println("strProveedor:  "+strProveedor);
        System.out.println("strPrioridad:  "+strPrioridad);
        System.out.println("strCreationDate:  "+strCreationDate);
        System.out.println("strDocument:  "+strDocument);
        System.out.println("strDocument1:  "+strDocument1);
        System.out.println("Se presiono el boton de buscar");
        fillTable(strProveedor, strPrioridad, strCreationDate);
    }//fin de public void getVariables(OAPageContext pageContext, OAWebBean webBean) 


    /**Container's getter for MasterVO1
     */
    public MasterVOImpl getMasterVO1() {
        return (MasterVOImpl)findViewObject("MasterVO1");
    }

    /**Container's getter for DetailVO1
     */
    public DetailVOImpl getDetailVO1() {
        return (DetailVOImpl)findViewObject("DetailVO1");
    }

    /**Container's getter for DetailVO2
     */
    public DetailVOImpl getDetailVO2() {
        return (DetailVOImpl)findViewObject("DetailVO2");
    }

    /**Container's getter for MasterDetailVL1
     */
    public ViewLinkImpl getMasterDetailVL1() {
        return (ViewLinkImpl)findViewLink("MasterDetailVL1");
    }

    public void MasterDetails(OAPageContext pageContext, OAWebBean webBean) {
        String strProveedor     = pageContext.getParameter("Proveedor");
        String strPrioridad     = pageContext.getParameter("Prioridad");
        OAMessageDateFieldBean oAMessageDateFieldBean = (OAMessageDateFieldBean)webBean.findChildRecursive("CreationDate");
        oracle.jbo.domain.Date strCreationDate = null;
        try {
            strCreationDate = new oracle.jbo.domain.Date(oAMessageDateFieldBean.getValue(pageContext));
        } catch (SQLException e) {
            System.out.println("No se encontro el campo tipo fecha");
        }
        String strDocument      = pageContext.getParameter("Document");
        String strDocument1     = pageContext.getParameter("Document1");
        System.out.println("strProveedor:  "+strProveedor);
        System.out.println("strPrioridad:  "+strPrioridad);
        System.out.println("strCreationDate:  "+strCreationDate);
        System.out.println("strDocument:  "+strDocument);
        System.out.println("strDocument1:  "+strDocument1);
        System.out.println("Se presiono el boton de buscar");
        fillTable(strProveedor, strPrioridad, strCreationDate);
        MasterVOImpl pvo = getMasterVO1(); 
        
        //creamos el criterio
        ViewCriteria vc = pvo.createViewCriteria();
        ViewCriteriaRow vcr1 = vc.createViewCriteriaRow();
        
        if(null != strProveedor && !"".equals(strProveedor)){
            System.out.println("Proveedor no nulo");
            vcr1.setAttribute("Provider",strProveedor);  
        }//fin de if(null != strProveedor)
        
        if(null != strPrioridad && !"".equals(strPrioridad)){
            System.out.println("Prioridad no nula");
            //vcr1.setAttribute();
        }//fin de if(null != strPrioridad)
        
        if(null != strCreationDate && !"".equals(strCreationDate)){
            System.out.println("Fecha de creacion no nula");   
            ///Date creaDate = (Date)strCreationDate.valueOf();
             System.out.println("strCreationDate:       "+strCreationDate);
            vcr1.setAttribute("CreationDate",strCreationDate);
        }//fin de if(null != strCreationDate)
        
        vcr1.setAttribute("Status","En proceso");
        vc.add(vcr1);
        pvo.applyViewCriteria(vc);
        pvo.executeQuery(); 
    }//fin de public void MasterDetails(OAPageContext pageContext, OAWebBean webBean)

    /**Container's getter for TotalsVO1
     */
    public TotalsVOImpl getTotalsVO1() {
        return (TotalsVOImpl)findViewObject("TotalsVO1");
    }
}

