package xxgam.oracle.apps.xbol.tm.request.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PruebaVORowImpl extends OAViewRowImpl {
    public static final int COL1 = 0;
    public static final int COL2 = 1;

    /**This is the default constructor (do not remove)
     */
    public PruebaVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Col1
     */
    public String getCol1() {
        return (String) getAttributeInternal(COL1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Col1
     */
    public void setCol1(String value) {
        setAttributeInternal(COL1, value);
    }

    /**Gets the attribute value for the calculated attribute Col2
     */
    public String getCol2() {
        return (String) getAttributeInternal(COL2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Col2
     */
    public void setCol2(String value) {
        setAttributeInternal(COL2, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case COL1:
            return getCol1();
        case COL2:
            return getCol2();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
