package xxgam.oracle.apps.xbol.tm.request.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import xxgam.oracle.apps.xbol.tm.RatesM.search.server.RatesVOImpl;
import xxgam.oracle.apps.xbol.tm.extracost.server.MasterVOImpl;
import oracle.apps.fnd.framework.webui.OAPageContext; 
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public RequestAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxgam.oracle.apps.xbol.tm.request.server", /* package name */
      "RequestAMLocal" /* Configuration Name */);
    }

    /**Container's getter for UnitOperVO1
     */
    public UnitOperVOImpl getUnitOperVO1() {
        return (UnitOperVOImpl)findViewObject("UnitOperVO1");
    }

    /**Container's getter for StatusVO1
     */
    public StatusVOImpl getStatusVO1() {
        return (StatusVOImpl)findViewObject("StatusVO1");
    }

    /**Container's getter for AreaVO1
     */
    public AreaVOImpl getAreaVO1() {
        return (AreaVOImpl)findViewObject("AreaVO1");
    }




    /**Container's getter for PruebaVO1
     */
    public PruebaVOImpl getPruebaVO1() {
        return (PruebaVOImpl)findViewObject("PruebaVO1");
    }
    
    public void fillTable1() {
        PruebaVOImpl pruebaVOImpl = getPruebaVO1();   
        pruebaVOImpl.executeQuery();
    }
}
