package xxgam.oracle.apps.xbol.tm.RatesM.search.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RatesVORowImpl extends OAViewRowImpl {
    public static final int IDTARIFA = 0;
    public static final int ORIGIN = 1;
    public static final int RZONE = 2;
    public static final int DESTINATION = 3;
    public static final int PROVIDERNUMBER = 4;
    public static final int PROVIDERNAME = 5;
    public static final int RMODE = 6;
    public static final int CURRENCY = 7;
    public static final int RATE = 8;
    public static final int MANEUVERS = 9;
    public static final int REPARTS = 10;
    public static final int INTERSECTION = 11;
    public static final int DATEFROM = 12;
    public static final int DATETO = 13;
    public static final int DISTRIBUTIONTYPE = 14;
    public static final int CLASSIFICATION = 15;
    public static final int TYPEV = 16;
    public static final int TYPED = 17;
    public static final int FLAG = 18;
    public static final int ATTRIBUTE1 = 19;
    public static final int ATTRIBUTE2 = 20;
    public static final int ATTRIBUTE3 = 21;
    public static final int ATTRIBUTE4 = 22;
    public static final int ATTRIBUTE5 = 23;
    public static final int ATTRIBUTE6 = 24;
    public static final int ATTRIBUTE7 = 25;
    public static final int ATTRIBUTE8 = 26;
    public static final int ATTRIBUTE9 = 27;
    public static final int ATTRIBUTE10 = 28;

    /**This is the default constructor (do not remove)
     */
    public RatesVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute IdTarifa
     */
    public Number getIdTarifa() {
        return (Number) getAttributeInternal(IDTARIFA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdTarifa
     */
    public void setIdTarifa(Number value) {
        setAttributeInternal(IDTARIFA, value);
    }

    /**Gets the attribute value for the calculated attribute Origin
     */
    public String getOrigin() {
        return (String) getAttributeInternal(ORIGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Origin
     */
    public void setOrigin(String value) {
        setAttributeInternal(ORIGIN, value);
    }

    /**Gets the attribute value for the calculated attribute RZone
     */
    public String getRZone() {
        return (String) getAttributeInternal(RZONE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RZone
     */
    public void setRZone(String value) {
        setAttributeInternal(RZONE, value);
    }

    /**Gets the attribute value for the calculated attribute Destination
     */
    public String getDestination() {
        return (String) getAttributeInternal(DESTINATION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Destination
     */
    public void setDestination(String value) {
        setAttributeInternal(DESTINATION, value);
    }

    /**Gets the attribute value for the calculated attribute ProviderNumber
     */
    public Number getProviderNumber() {
        return (Number) getAttributeInternal(PROVIDERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProviderNumber
     */
    public void setProviderNumber(Number value) {
        setAttributeInternal(PROVIDERNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute ProviderName
     */
    public String getProviderName() {
        return (String) getAttributeInternal(PROVIDERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProviderName
     */
    public void setProviderName(String value) {
        setAttributeInternal(PROVIDERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute RMode
     */
    public String getRMode() {
        return (String) getAttributeInternal(RMODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RMode
     */
    public void setRMode(String value) {
        setAttributeInternal(RMODE, value);
    }

    /**Gets the attribute value for the calculated attribute Currency
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**Gets the attribute value for the calculated attribute Rate
     */
    public String getRate() {
        return (String) getAttributeInternal(RATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Rate
     */
    public void setRate(String value) {
        setAttributeInternal(RATE, value);
    }

    /**Gets the attribute value for the calculated attribute Maneuvers
     */
    public String getManeuvers() {
        return (String) getAttributeInternal(MANEUVERS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Maneuvers
     */
    public void setManeuvers(String value) {
        setAttributeInternal(MANEUVERS, value);
    }

    /**Gets the attribute value for the calculated attribute Reparts
     */
    public String getReparts() {
        return (String) getAttributeInternal(REPARTS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Reparts
     */
    public void setReparts(String value) {
        setAttributeInternal(REPARTS, value);
    }

    /**Gets the attribute value for the calculated attribute Intersection
     */
    public String getIntersection() {
        return (String) getAttributeInternal(INTERSECTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Intersection
     */
    public void setIntersection(String value) {
        setAttributeInternal(INTERSECTION, value);
    }

    /**Gets the attribute value for the calculated attribute DateFrom
     */
    public Date getDateFrom() {
        return (Date) getAttributeInternal(DATEFROM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DateFrom
     */
    public void setDateFrom(Date value) {
        setAttributeInternal(DATEFROM, value);
    }

    /**Gets the attribute value for the calculated attribute DateTo
     */
    public Date getDateTo() {
        return (Date) getAttributeInternal(DATETO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DateTo
     */
    public void setDateTo(Date value) {
        setAttributeInternal(DATETO, value);
    }

    /**Gets the attribute value for the calculated attribute DistributionType
     */
    public String getDistributionType() {
        return (String) getAttributeInternal(DISTRIBUTIONTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DistributionType
     */
    public void setDistributionType(String value) {
        setAttributeInternal(DISTRIBUTIONTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute Classification
     */
    public String getClassification() {
        return (String) getAttributeInternal(CLASSIFICATION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Classification
     */
    public void setClassification(String value) {
        setAttributeInternal(CLASSIFICATION, value);
    }

    /**Gets the attribute value for the calculated attribute TypeV
     */
    public Number getTypeV() {
        return (Number) getAttributeInternal(TYPEV);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TypeV
     */
    public void setTypeV(Number value) {
        setAttributeInternal(TYPEV, value);
    }

    /**Gets the attribute value for the calculated attribute TypeD
     */
    public String getTypeD() {
        return (String) getAttributeInternal(TYPED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TypeD
     */
    public void setTypeD(String value) {
        setAttributeInternal(TYPED, value);
    }

    /**Gets the attribute value for the calculated attribute Flag
     */
    public String getFlag() {
        return (String) getAttributeInternal(FLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Flag
     */
    public void setFlag(String value) {
        setAttributeInternal(FLAG, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDTARIFA:
            return getIdTarifa();
        case ORIGIN:
            return getOrigin();
        case RZONE:
            return getRZone();
        case DESTINATION:
            return getDestination();
        case PROVIDERNUMBER:
            return getProviderNumber();
        case PROVIDERNAME:
            return getProviderName();
        case RMODE:
            return getRMode();
        case CURRENCY:
            return getCurrency();
        case RATE:
            return getRate();
        case MANEUVERS:
            return getManeuvers();
        case REPARTS:
            return getReparts();
        case INTERSECTION:
            return getIntersection();
        case DATEFROM:
            return getDateFrom();
        case DATETO:
            return getDateTo();
        case DISTRIBUTIONTYPE:
            return getDistributionType();
        case CLASSIFICATION:
            return getClassification();
        case TYPEV:
            return getTypeV();
        case TYPED:
            return getTypeD();
        case FLAG:
            return getFlag();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
