package xxgam.oracle.apps.xbol.tm.RatesM.search.server;

import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RatesMAMDefImpl extends ApplicationModuleDefImpl {
    /**This is the default constructor (do not remove)
     */
    public RatesMAMDefImpl() {
    }
}
